version: '3.8'

services:
  postgres-master:
    build: ./postgres-master
    container_name: postgres-master
    hostname: postgres-master
    privileged: true
    ports:
      - "5433:5433"
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
    networks:
      postgres-network:
        ipv4_address: 172.20.0.10

  postgres-standby:
    build: ./postgres-standby
    container_name: postgres-standby
    hostname: postgres-standby
    ports:
      - "5434:5433"
    volumes:
      - postgres-standby-data:/var/lib/postgresql/data
    networks:
      postgres-network:
        ipv4_address: 172.20.0.11

  pgpool-client:
    build: ./pgpool-client
    container_name: pgpool-client
    hostname: pgpool-client
    ports:
      - "5432:5432" # для pgpool
    networks:
      postgres-network:
        ipv4_address: 172.20.0.12

networks:
  postgres-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres-master-data:
  postgres-standby-data:
